### ISSUE TITLE
`wstcp` process high cpu usage (perhaps harmless)

### ISSUE THREAD

**Issue by unicolet** [sile/wstcp#2]
Perhaps it's harmless, but I noticed `wstcp` shows high cpu usage in htop:

![image](https://user-images.githubusercontent.com/599127/81377540-005abf80-9106-11ea-8ec5-13239a061da7.png)

a quick strace show `nanosleep` seems to be called in a loop, this is a quick excerpt:

```
nanosleep({tv_sec=0, tv_nsec=1000000}, 0x7ffc46b3a770) = 0
nanosleep({tv_sec=0, tv_nsec=1000000}, 0x7ffc46b3a770) = 0
nanosleep({tv_sec=0, tv_nsec=1000000}, 0x7ffc46b3a770) = 0
```

can reproduce with versions `0.1.1` and `0.1.5`, so perhaps this is something happening in an underlying library? I tried googling but could not find much.
Thanks in advance

**Comment by sile** [comment]
Hi @unicolet, thank you for reporting t this issue.

I think that this is due to the polling loop of [`fibers`](https://github.com/dwango/fibers-rs) which is a `Future` runtime used in `wstcp-v0.1.*`. 
I tried switching the runtime to [`async-std`](https://github.com/async-rs/async-std)(#3) and published v0.2.0, so this problem may be mitigated in the latest version (I'm not sure though).

**Comment by unicolet** [comment]
@sile wow, thanks for the quick feedback ❤️ I will check and get back to you asap

**Comment by unicolet** [comment]
from a quick local run the issue seems to have disappeared. I will roll out the change and the report back progress

**Comment by unicolet** [comment]
@sile deployed and running for a few days without issues (it does receive very light usage though). Thanks for the excellent help

**Comment by sile** [comment]
Wow, it's good news! Thank you for confirming it!
